title: ValuCompass Support
description: Help articles for ValuCompass

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

logo: /assets/images/logo.webp
# optional, but safe:
search_enabled: true

baseurl: /support-docs