title: ValuCompass Support
description: Help articles for ValuCompass

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Optional polish
# logo: /assets/images/logo.png
search_enabled: true
color_scheme: default

